# Generated by Django 5.1.6 on 2025-03-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price_60', models.IntegerField(default=0)),
                ('price_75', models.IntegerField(default=0)),
                ('price_90', models.IntegerField(default=0)),
                ('price_120', models.IntegerField(default=0)),
                ('price_150', models.IntegerField(default=0)),
                ('price_180', models.IntegerField(default=0)),
                ('price_extension_30', models.IntegerField(default=0)),
                ('plus_per_star', models.IntegerField(default=1000)),
            ],
        ),
        migrations.AddField(
            model_name='storeuser',
            name='star_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ニックネーム'),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.rank'),
        ),
    ]
