# Generated by Django 5.1.6 on 2025-03-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_storeuser_rank_alter_storeuser_star_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cast_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='キャスト写真'),
        ),
    ]
