# Generated by Django 5.1.6 on 2025-03-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_cast_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cast_photo',
        ),
        migrations.AddField(
            model_name='storeuser',
            name='cast_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='キャスト写真'),
        ),
    ]
