# Generated by Django 5.2.1 on 2025-07-16 05:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billitem',
            options={},
        ),
        migrations.RenameField(
            model_name='billitem',
            old_name='session',
            new_name='bill',
        ),
        migrations.RenameField(
            model_name='billitem',
            old_name='by_cast',
            new_name='served_by_cast',
        ),
        migrations.AddField(
            model_name='castpayout',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='billing.bill'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='category',
            field=models.CharField(default='drink', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='nominated_casts',
            field=models.ManyToManyField(blank=True, related_name='nominated_bills', to='billing.cast'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='back_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='castpayout',
            name='bill_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='billing.billitem'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='default_back_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=4),
        ),
    ]
