# Generated by Django 5.2.1 on 2025-07-16 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_billitem_options_rename_session_billitem_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
