# Generated by Django 5.2.1 on 2025-07-16 07:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_bill_opened_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billitem',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='itemmaster',
            old_name='default_price',
            new_name='price_regular',
        ),
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billitem',
            name='exclude_from_payout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billitem',
            name='is_nomination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billitem',
            name='is_table_drink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cast',
            name='back_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='apply_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='exclude_from_payout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='price_late',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='track_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='category',
            field=models.CharField(choices=[('set', 'セット'), ('drink', 'ドリンク'), ('bottle', 'ボトル'), ('fee', '各種料金')], default='drink', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='service_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='store',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4),
        ),
        migrations.CreateModel(
            name='ItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='billing.itemmaster')),
            ],
        ),
    ]
