# Generated by Django 5.2.1 on 2025-07-16 07:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_billitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('default_back_rate', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=4)),
            ],
        ),
    ]
