# Generated by Django 5.2.1 on 2025-07-16 07:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_itemcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='back_rate_override',
            new_name='back_rate_free_override',
        ),
        migrations.RenameField(
            model_name='itemcategory',
            old_name='default_back_rate',
            new_name='back_rate_free',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='back_rate',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='is_table_drink',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='default_back_rate',
        ),
        migrations.AddField(
            model_name='billitem',
            name='is_inhouse',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='back_rate_inhouse_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='cast',
            name='back_rate_nomination_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='back_rate_inhouse',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=4),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='back_rate_nomination',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='exclude_from_payout',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='is_nomination',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='castpayout',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='billing.bill'),
        ),
        migrations.AlterField(
            model_name='castpayout',
            name='cast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.cast'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.itemcategory'),
        ),
        migrations.CreateModel(
            name='BillCastStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='billing.bill')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.cast')),
            ],
        ),
    ]
