# Generated by Django 5.2.1 on 2025-07-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_rename_back_rate_override_cast_back_rate_free_override_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billcaststay',
            options={'ordering': ['entered_at']},
        ),
        migrations.AddField(
            model_name='billcaststay',
            name='stay_type',
            field=models.CharField(choices=[('free', 'フリー'), ('in', '場内指名'), ('nom', '本指名')], default='free', max_length=4),
        ),
        migrations.AlterField(
            model_name='billcaststay',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.bill'),
        ),
    ]
