# Generated by Django 5.2.1 on 2025-07-16 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_billcaststay_options_billcaststay_stay_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.store'),
        ),
    ]
