# Generated by Django 5.2.1 on 2025-07-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_cast_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcaststay',
            name='is_inhouse',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
