# Generated by Django 5.2.1 on 2025-07-17 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_billcaststay_is_inhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcaststay',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='billing.bill'),
        ),
    ]
