# Generated by Django 5.2.1 on 2025-07-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_userstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='duration_min',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='category',
            field=models.CharField(choices=[('set', 'セット'), ('drink', 'ドリンク'), ('food', 'フード')], default='drink', max_length=16),
        ),
    ]
