# Generated by Django 5.2.1 on 2025-07-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_itemmaster_duration_min_alter_itemmaster_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='category',
            field=models.CharField(choices=[('set', 'セット'), ('ext', '延長'), ('drink', 'ドリンク')], default='drink', max_length=8),
        ),
    ]
