# Generated by Django 5.2.1 on 2025-07-18 06:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_itemmaster_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
