# Generated by Django 5.2.1 on 2025-07-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_cast_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
