# Generated by Django 5.2.1 on 2025-07-18 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_itemmaster_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.table'),
        ),
    ]
