# Generated by Django 5.2.1 on 2025-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_bill_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='grand_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='service_charge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
