# Generated by Django 5.2.1 on 2025-07-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_bill_grand_total_bill_service_charge_bill_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='settled_total',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
