# Generated by Django 5.2.1 on 2025-07-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_billinguser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name': 'キャスト登録'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['store', 'number'], 'verbose_name': 'テーブル番号'},
        ),
    ]
