# Generated by Django 5.2.1 on 2025-07-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_alter_cast_options_alter_table_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name': 'キャスト登録', 'verbose_name_plural': 'キャスト登録'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['store', 'number'], 'verbose_name': 'テーブル番号', 'verbose_name_plural': 'テーブル番号'},
        ),
    ]
