# Generated by Django 5.2.1 on 2025-07-23 08:50

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_alter_cast_options_alter_table_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name': 'キャスト', 'verbose_name_plural': 'キャスト'},
        ),
        migrations.AlterField(
            model_name='cast',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='アバター'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='back_rate_free_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='バック率（フリー）'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='back_rate_inhouse_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='バック率（場内）'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='back_rate_nomination_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='バック率（指名）'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='stage_name',
            field=models.CharField(max_length=50, verbose_name='源氏名'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.store', verbose_name='店舗'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
