# Generated by Django 5.2.1 on 2025-07-23 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_alter_cast_options_alter_cast_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_wage', models.PositiveIntegerField(default=1300, verbose_name='時給')),
                ('stores', models.ManyToManyField(blank=True, related_name='staff_members', to='billing.store', verbose_name='所属店舗')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'スタッフ',
                'verbose_name_plural': 'スタッフ',
            },
        ),
    ]
