# Generated by Django 5.2.1 on 2025-07-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': '伝票', 'verbose_name_plural': '伝票'},
        ),
        migrations.AddField(
            model_name='bill',
            name='expected_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退店予定'),
        ),
    ]
