# Generated by Django 5.2.1 on 2025-07-25 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_backfill_expected_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='billing.itemcategory', null=True),
        ),
    ]
