# Generated by Django 5.2.1 on 2025-07-25 04:56

from django.db import migrations

def forwards(apps, schema_editor):
    ItemMaster   = apps.get_model('billing', 'ItemMaster')
    ItemCategory = apps.get_model('billing', 'ItemCategory')

    # 文字列だった旧値 → 同じ code を持つ Category へ置き換え
    for im in ItemMaster.objects.all():
        if isinstance(im.category, str):
            try:
                cat = ItemCategory.objects.get(code=im.category)
                im.category = cat
                im.save(update_fields=['category'])
            except ItemCategory.DoesNotExist:
                # 未登録コードはとりあえず None に
                im.category = None
                im.save(update_fields=['category'])

class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0026_alter_itemmaster_category'),
    ]
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]

