# Generated by Django 5.2.1 on 2025-07-28 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_enforce_itemmaster_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castpayout',
            name='cast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='billing.cast'),
        ),
    ]
