# Generated by Django 5.2.1 on 2025-07-28 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_alter_castpayout_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastCategoryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_free', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rate_nomination', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rate_inhouse', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rates', to='billing.cast')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.itemcategory')),
            ],
            options={
                'unique_together': {('cast', 'category')},
            },
        ),
    ]
