# Generated by Django 5.2.1 on 2025-07-28 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_castcategoryrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='main_cast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_bills', to='billing.cast', verbose_name='本指名'),
        ),
    ]
