# Generated by Django 5.2.1 on 2025-07-28 07:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_bill_main_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcaststay',
            name='nom_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='この伝票だけの本指名バック用ウェイト。未入力なら1扱い', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='nom_pool_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, verbose_name='本指名率'),
        ),
    ]
