# Generated by Django 5.2.1 on 2025-07-29 04:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_billcaststay_nom_weight_store_nom_pool_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='出勤時刻')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='退勤時刻')),
                ('hourly_wage_snap', models.PositiveIntegerField(blank=True, null=True, verbose_name='時給スナップ')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.cast')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.store')),
            ],
            options={
                'verbose_name': 'キャストシフト',
                'verbose_name_plural': 'キャストシフト',
                'ordering': ['-clock_in'],
                'unique_together': {('store', 'cast', 'clock_in')},
            },
        ),
    ]
