# Generated by Django 5.2.1 on 2025-07-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_castshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='hourly_wage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='時給'),
        ),
    ]
