# Generated by Django 5.2.1 on 2025-07-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_cast_hourly_wage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castshift',
            options={'ordering': ['-plan_start'], 'verbose_name': 'キャストシフト', 'verbose_name_plural': 'キャストシフト'},
        ),
        migrations.AlterUniqueTogether(
            name='castshift',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='castshift',
            name='plan_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='予定終了'),
        ),
        migrations.AddField(
            model_name='castshift',
            name='plan_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='予定開始'),
        ),
        migrations.AlterField(
            model_name='castshift',
            name='clock_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出勤'),
        ),
        migrations.AlterField(
            model_name='castshift',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退勤'),
        ),
        migrations.AlterField(
            model_name='castshift',
            name='hourly_wage_snap',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
