# Generated by Django 5.2.1 on 2025-07-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_alter_castshift_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='castshift',
            name='worked_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='勤務分'),
        ),
    ]
