# Generated by Django 5.2.1 on 2025-07-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_castshift_worked_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='castshift',
            name='payroll_amount',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='給与額'),
        ),
        migrations.AlterField(
            model_name='castshift',
            name='hourly_wage_snap',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='時給スナップ'),
        ),
        migrations.AlterField(
            model_name='castshift',
            name='worked_min',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='勤務分'),
        ),
    ]
