# Generated by Django 5.2.1 on 2025-07-29 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_castshift_payroll_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('worked_min', models.PositiveIntegerField(default=0)),
                ('payroll', models.PositiveIntegerField(default=0)),
                ('sales_free', models.PositiveIntegerField(default=0)),
                ('sales_in', models.PositiveIntegerField(default=0)),
                ('sales_nom', models.PositiveIntegerField(default=0)),
                ('sales_champ', models.PositiveIntegerField(default=0)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.cast')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.store')),
            ],
            options={
                'verbose_name': 'キャスト日次サマリ',
                'verbose_name_plural': 'キャスト日次サマリ',
                'indexes': [models.Index(fields=['work_date'], name='billing_cas_work_da_b321dc_idx'), models.Index(fields=['cast', 'work_date'], name='billing_cas_cast_id_a807bb_idx')],
                'unique_together': {('store', 'cast', 'work_date')},
            },
        ),
    ]
