# Generated by Django 5.2.1 on 2025-07-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0038_castdailysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='show_in_menu',
            field=models.BooleanField(default=False, verbose_name='POSメニューに表示'),
        ),
    ]
