# Generated by Django 5.2.1 on 2025-08-01 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0039_itemcategory_show_in_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('amount_off', models.PositiveIntegerField(blank=True, null=True)),
                ('percent_off', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '割引ルール',
                'verbose_name_plural': '割引ルール',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='discount_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.discountrule'),
        ),
    ]
