# Generated by Django 5.2.1 on 2025-08-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0042_userstore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStore',
        ),
    ]
