# Generated by Django 5.2.1 on 2025-08-04 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0043_delete_userstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castdailysummary',
            name='cast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='billing.cast'),
        ),
    ]
