# Generated by Django 5.2.1 on 2025-08-05 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0044_alter_castdailysummary_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_start', models.DateTimeField(blank=True, null=True, verbose_name='予定開始')),
                ('plan_end', models.DateTimeField(blank=True, null=True, verbose_name='予定終了')),
                ('clock_in', models.DateTimeField(blank=True, null=True, verbose_name='出勤')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='退勤')),
                ('hourly_wage_snap', models.PositiveIntegerField(blank=True, null=True, verbose_name='時給スナップ')),
                ('worked_min', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='勤務分')),
                ('payroll_amount', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='給与額')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.staff')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.store')),
            ],
            options={
                'verbose_name': 'スタッフシフト',
                'verbose_name_plural': 'スタッフシフト',
                'ordering': ['-plan_start'],
            },
        ),
    ]
