# Generated by Django 5.2.1 on 2025-08-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0045_staffshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('staff', 'スタッフ'), ('submgr', '副店長'), ('mgr', '店長')], default='staff', max_length=10, verbose_name='役職'),
        ),
    ]
