# Generated by Django 5.2.1 on 2025-08-07 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0049_bill_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.bill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.customer')),
            ],
            options={
                'unique_together': {('bill', 'customer')},
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='bills', through='billing.BillCustomer', to='billing.customer'),
        ),
    ]
