# Generated by Django 5.2.1 on 2025-08-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0050_billcustomer_bill_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
    ]
