# Generated by Django 5.2.1 on 2025-08-10 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0052_bill_paid_card_bill_paid_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='castdailysummary',
            name='business_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='business_day_cutoff_hour',
            field=models.PositiveSmallIntegerField(default=6, help_text='営業日の切替時刻（例: 6 = 朝6時締め。20:00-26:00 の場合は 6 推奨）', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
