# Generated by Django 5.2.1 on 2025-08-10 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0053_castdailysummary_business_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='store_notices/%Y/%m/')),
                ('is_published', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='billing.store')),
            ],
            options={
                'ordering': ['-pinned', '-publish_at', '-created_at'],
                'indexes': [models.Index(fields=['store', 'is_published', 'publish_at'], name='billing_sto_store_i_242697_idx'), models.Index(fields=['pinned'], name='billing_sto_pinned_76ef3c_idx'), models.Index(fields=['created_at'], name='billing_sto_created_49495f_idx')],
            },
        ),
    ]
