# Generated by Django 5.2.1 on 2025-09-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0054_storenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='route',
            field=models.CharField(choices=[('none', 'なし'), ('kitchen', 'キッチン'), ('drinker', 'ドリンカー')], db_index=True, default='none', help_text='KDSの行き先。キッチン/ドリンカー/対象外', max_length=16),
        ),
    ]
