# Generated by Django 5.2.1 on 2025-09-04 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0055_itemmaster_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(db_index=True, default='none', max_length=16)),
                ('state', models.CharField(choices=[('new', 'NEW'), ('ack', 'ACK'), ('ready', 'READY')], db_index=True, default='new', max_length=16)),
                ('created_by_cast', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='billing.billitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.store')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['store', 'route', 'state', '-created_at'], name='billing_ord_store_i_5770df_idx')],
            },
        ),
    ]
