# Generated by Django 5.2.1 on 2025-09-04 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0056_orderticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='taken_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_tickets', to='billing.staff'),
        ),
        migrations.AddIndex(
            model_name='orderticket',
            index=models.Index(fields=['store', 'state', 'archived_at'], name='billing_ord_store_i_81cc02_idx'),
        ),
    ]
