# Generated by Django 5.2.1 on 2025-09-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0057_orderticket_archived_at_orderticket_taken_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='route',
            field=models.CharField(choices=[('none', 'なし'), ('kitchen', 'キッチン'), ('drinker', 'ドリンカー')], db_index=True, default='none', help_text='このカテゴリのKDS行き先（フード=キッチン、ドリンク=ドリンカー等）', max_length=16),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='route',
            field=models.CharField(choices=[('inherit', 'カテゴリ継承'), ('none', 'なし'), ('kitchen', 'キッチン'), ('drinker', 'ドリンカー')], db_index=True, default='inherit', help_text='KDS行き先。通常は「カテゴリ継承」。必要時のみ個別上書き', max_length=16),
        ),
    ]
