# Generated by Django 5.2.1 on 2025-09-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0059_billcaststay_is_honshimei'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='メモ'),
        ),
    ]
