# Generated by Django 5.2.1 on 2025-09-17 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0060_bill_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('revenue', '売上金額'), ('nominations', '本指名本数'), ('inhouse', '場内指名本数'), ('champ_revenue', 'シャンパン売上'), ('champ_count', 'シャンパン本数')], max_length=24)),
                ('target_value', models.IntegerField()),
                ('period_kind', models.CharField(choices=[('daily', '日次'), ('weekly', '週次'), ('monthly', '月次'), ('custom', 'カスタム')], default='daily', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('milestones_hit', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='billing.cast')),
            ],
            options={
                'indexes': [models.Index(fields=['cast', 'metric', 'period_kind', 'start_date', 'end_date', 'active'], name='billing_cas_cast_id_7b283f_idx')],
            },
        ),
    ]
