# Generated by Django 5.2.1 on 2025-09-24 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0061_castgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='seat_type',
            field=models.CharField(choices=[('main', 'メイン'), ('counter', 'カウンター'), ('box', 'ボックス')], db_index=True, default='main', max_length=16),
        ),
        migrations.CreateModel(
            name='StoreSeatSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('main', 'メイン'), ('counter', 'カウンター'), ('box', 'ボックス')], db_index=True, max_length=16)),
                ('service_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('charge_per_person', models.PositiveIntegerField(blank=True, null=True)),
                ('extension_30_price', models.PositiveIntegerField(blank=True, null=True)),
                ('free_time_price', models.PositiveIntegerField(blank=True, null=True)),
                ('private_price', models.PositiveIntegerField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, default='', max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_settings', to='billing.store')),
            ],
            options={
                'verbose_name': '席種設定',
                'verbose_name_plural': '席種設定',
                'unique_together': {('store', 'seat_type')},
            },
        ),
    ]
