# Generated by Django 5.2.1 on 2025-09-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0062_table_seat_type_storeseatsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountrule',
            options={'ordering': ['-created_at'], 'verbose_name': '割引ルール', 'verbose_name_plural': '割引ルール'},
        ),
        migrations.AddField(
            model_name='discountrule',
            name='code',
            field=models.SlugField(blank=True, help_text='内部コード（例: initial / agency / referral）', max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='name',
            field=models.CharField(help_text='表示名（例: 初回 / 案内所 / 顧客紹介）', max_length=40),
        ),
    ]
