# Generated by Django 5.2.1 on 2025-09-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0064_fill_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountrule',
            name='is_basic',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
