# Generated by Django 5.2.1 on 2025-09-25 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0066_alter_table_options_alter_table_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['store', 'code'], 'verbose_name': 'テーブル番号', 'verbose_name_plural': 'テーブル番号'},
        ),
        migrations.AlterField(
            model_name='table',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='例: T01, B02（英数字可）', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='英数字・ハイフン・アンダースコアのみ（1〜16文字）。例: T01, B02', regex='^[A-Za-z0-9_-]{1,16}$')]),
        ),
    ]
