# Generated by Django 5.2.1 on 2025-10-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0068_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcaststay',
            name='is_dohoan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billcaststay',
            name='stay_type',
            field=models.CharField(choices=[('free', 'フリー'), ('in', '場内指名'), ('nom', '本指名'), ('dohan', '同伴')], db_index=True, max_length=16),
        ),
    ]
