# Generated by Django 5.2.1 on 2025-10-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0069_billcaststay_is_dohoan_alter_billcaststay_stay_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billcaststay',
            old_name='is_dohoan',
            new_name='is_dohan',
        ),
    ]
