# Generated by Django 5.2.1 on 2025-10-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0070_rename_is_dohoan_billcaststay_is_dohan'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemmaster',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='uniq_store_code'),
        ),
    ]
