# Generated by Django 5.2.1 on 2025-10-27 07:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0071_itemmaster_uniq_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='back_rate_dohan_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='back_rate_free_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='back_rate_inhouse_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='back_rate_nomination_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='is_inhouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='is_nomination',
            field=models.BooleanField(default=False),
        ),
    ]
