# Generated by Django 5.2.1 on 2025-10-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0072_store_back_rate_dohan_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='payout_fixed_per_item',
            field=models.PositiveIntegerField(blank=True, help_text='固定バック（円/個）。例: ボトル=500', null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='use_fixed_payout_free_in',
            field=models.BooleanField(default=False, help_text='フリー/場内は％ではなく固定額(円)で支払う'),
        ),
    ]
