# Generated by Django 5.2.1 on 2025-10-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0073_itemcategory_payout_fixed_per_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcategory',
            name='payout_fixed_per_item',
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='use_fixed_payout_free_in',
            field=models.BooleanField(default=False, help_text='ボトル判定後はpayroll/engines', verbose_name='ボトル判定'),
        ),
    ]
