# Generated by Django 5.2.1 on 2025-10-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0074_remove_itemcategory_payout_fixed_per_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='payout_fixed_per_item',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
