# Generated by Django 5.2.1 on 2025-11-05 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0075_itemcategory_payout_fixed_per_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountrule',
            options={'ordering': ['store', 'sort_order', '-created_at'], 'verbose_name': '割引ルール', 'verbose_name_plural': '割引ルール'},
        ),
        migrations.AddField(
            model_name='discountrule',
            name='show_in_basics',
            field=models.BooleanField(default=True, help_text='Basicパネルに表示する'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='show_in_pay',
            field=models.BooleanField(default=True, help_text='会計パネルに表示する'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='store',
            field=models.ForeignKey(blank=True, help_text='この割引ルールを適用できる店舗', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='billing.store'),
        ),
        migrations.AddConstraint(
            model_name='discountrule',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('code__isnull', True), _negated=True), models.Q(('code', ''), _negated=True)), fields=('store', 'code'), name='uniq_store_code_on_discount_rule'),
        ),
    ]
