# Generated by Django 5.2.1 on 2025-11-07 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0081_finalize_seattype_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeseatsetting',
            name='seat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.seattype'),
        ),
        migrations.AlterField(
            model_name='table',
            name='seat_type',
            field=models.ForeignKey(blank=True, help_text='席種（未設定可）', null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.seattype'),
        ),
    ]
