# Generated by Django 5.2.1 on 2025-11-11 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0082_alter_storeseatsetting_seat_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDiscountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='割引明細')),
                ('amount', models.PositiveIntegerField(verbose_name='金額（円・正の値）')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_discounts', to='billing.bill')),
            ],
            options={
                'verbose_name': '手入力割引明細',
                'verbose_name_plural': '手入力割引明細',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
