# Generated by Django 5.2.1 on 2025-11-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0083_billdiscountline'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcaststay',
            name='is_help',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
