# Generated by Django 5.2.1 on 2025-12-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0085_billitem_is_dohan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='内部コード（例: vip / regular / newcomer）', max_length=40, unique=True)),
                ('name', models.CharField(help_text='表示名（例: VIP / 常連 / 新規）', max_length=50)),
                ('description', models.TextField(blank=True, help_text='説明・使用ガイドライン')),
                ('color', models.CharField(blank=True, default='#808080', help_text='UI表示用カラーコード（例: #FF5733）', max_length=7)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '顧客タグ',
                'verbose_name_plural': '顧客タグ',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='customers', to='billing.customertag', verbose_name='属性タグ'),
        ),
    ]
