# Generated by Django 5.2.1 on 2025-12-11 10:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0086_customertag_customer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='back_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
