# Generated by Django 5.2.1 on 2025-12-15 06:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0087_billitem_back_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='集計日（YYYY-MM-DD）')),
                ('hour', models.IntegerField(help_text='時刻（0-23）', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('sales_total', models.PositiveIntegerField(default=0, help_text='売上合計')),
                ('bill_count', models.PositiveIntegerField(default=0, help_text='伝票数')),
                ('customer_count', models.PositiveIntegerField(default=0, help_text='来客数')),
                ('sales_set', models.PositiveIntegerField(default=0, help_text='セット売上')),
                ('sales_drink', models.PositiveIntegerField(default=0, help_text='ドリンク売上')),
                ('sales_food', models.PositiveIntegerField(default=0, help_text='フード売上')),
                ('sales_champagne', models.PositiveIntegerField(default=0, help_text='シャンパン売上')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_summaries', to='billing.store')),
            ],
            options={
                'verbose_name': '時間別売上サマリ',
                'verbose_name_plural': '時間別売上サマリ',
                'ordering': ['date', 'hour'],
            },
        ),
        migrations.CreateModel(
            name='HourlyCastSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_total', models.PositiveIntegerField(default=0, help_text='このキャストの売上合計')),
                ('sales_nom', models.PositiveIntegerField(default=0, help_text='本指名売上')),
                ('sales_in', models.PositiveIntegerField(default=0, help_text='場内指名売上')),
                ('sales_free', models.PositiveIntegerField(default=0, help_text='フリー売上')),
                ('sales_champagne', models.PositiveIntegerField(default=0, help_text='シャンパン売上')),
                ('bill_count', models.PositiveIntegerField(default=0, help_text='担当伝票数')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_sales', to='billing.cast')),
                ('hourly_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_breakdown', to='billing.hourlysalessummary')),
            ],
            options={
                'verbose_name': '時間別キャスト売上',
                'verbose_name_plural': '時間別キャスト売上',
                'ordering': ['-sales_total'],
            },
        ),
        migrations.AddIndex(
            model_name='hourlysalessummary',
            index=models.Index(fields=['store', 'date', 'hour'], name='billing_hou_store_i_8d3fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='hourlysalessummary',
            index=models.Index(fields=['date', 'hour'], name='billing_hou_date_896cb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hourlysalessummary',
            unique_together={('store', 'date', 'hour')},
        ),
        migrations.AddIndex(
            model_name='hourlycastsales',
            index=models.Index(fields=['cast', 'hourly_summary'], name='billing_hou_cast_id_e3f565_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hourlycastsales',
            unique_together={('hourly_summary', 'cast')},
        ),
    ]
