# Generated by Django 5.2.1 on 2025-12-15 07:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0088_hourlysalessummary_hourlycastsales_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourlysalessummary',
            options={},
        ),
        migrations.AddField(
            model_name='store',
            name='business_close_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('27.0'), help_text='営業終了時刻（営業日内の相対時刻。例: 27.0 = 朝3:00）', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(27)]),
        ),
        migrations.AddField(
            model_name='store',
            name='business_open_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.0'), help_text='営業開始時刻（営業日内の相対時刻。例: 20.0 = 20:00）', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(27)]),
        ),
        migrations.AlterField(
            model_name='store',
            name='business_day_cutoff_hour',
            field=models.PositiveSmallIntegerField(default=6, help_text='営業日の切替時刻（例: 6 = 朝6時締め。営業日外の処理に使用）', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
