# Generated by Django 5.2.1 on 2025-12-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0089_add_business_hours_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bottle_memo',
            field=models.TextField(blank=True, help_text='銘柄や残量など（例: ジャックダニエル 3/4残）', verbose_name='ボトルメモ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bottle_shelf',
            field=models.CharField(blank=True, help_text='ボトルの保管場所（例: A-12, B-5）', max_length=50, verbose_name='棚番号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_bottle',
            field=models.BooleanField(default=False, help_text='マイボトルを預けているか', verbose_name='マイボトル有無'),
        ),
    ]
