# Generated by Django 5.2.1 on 2025-12-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0090_add_customer_bottle_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('paid_cash__gte', 0), ('paid_cash__lte', 100000000)), name='bill_paid_cash_range'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('paid_card__gte', 0), ('paid_card__lte', 100000000)), name='bill_paid_card_range'),
        ),
        migrations.AddConstraint(
            model_name='billitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', 1), ('qty__lte', 99)), name='billitem_qty_range'),
        ),
        migrations.AddConstraint(
            model_name='billitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0), ('price__lte', 2000000)), name='billitem_price_range'),
        ),
    ]
