# Generated by Django 5.2.1 on 2025-12-16 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0091_bill_bill_paid_cash_range_bill_bill_paid_card_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='opened_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
