# Generated by GitHub Copilot on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0092_alter_bill_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pax',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='人数'),
        ),
    ]
