# Generated by Django 5.2.1 on 2025-12-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0100_populate_itemcategory_major_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='major_group',
            field=models.CharField(choices=[('drink', 'ドリンク'), ('champagne', 'シャンパン'), ('food', 'フード'), ('other', 'その他商品'), ('set', 'セット（人数）'), ('extension', '延長'), ('other_fee', 'その他料金')], default='other', help_text='集計用の大カテゴリ（7種類で固定）', max_length=20),
        ),
    ]
