# Generated by Django 5.2.1 on 2025-12-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0101_alter_itemcategory_major_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payroll_snapshot',
            field=models.JSONField(blank=True, help_text='クローズ時点の給与内訳を保存（不変）', null=True, verbose_name='給与スナップショット'),
        ),
    ]
