# Generated by Django 5.2.1 on 2025-12-22 03:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0102_bill_payroll_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='payroll_cutoff_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text="給与締め日（kind='day'のとき必須。例: 25締め）", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='store',
            name='payroll_cutoff_kind',
            field=models.CharField(choices=[('day', '日付'), ('eom', '月末')], default='day', help_text='給与締め基準（日付 or 月末）', max_length=10),
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='期間開始日')),
                ('period_end', models.DateField(verbose_name='期間終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('overlap_warning', models.BooleanField(default=False, help_text='既存の締め期間と重複している場合 True', verbose_name='重複警告')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='billing.store')),
            ],
            options={
                'verbose_name': '給与締め',
                'verbose_name_plural': '給与締め',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRunBackRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.IntegerField(blank=True, null=True, verbose_name='伝票ID')),
                ('bill_item_id', models.IntegerField(blank=True, null=True, verbose_name='明細ID')),
                ('occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='発生日時')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='バック額')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.cast', verbose_name='キャスト')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_rows', to='billing.payrollrun')),
            ],
            options={
                'verbose_name': '給与締めバック根拠',
                'verbose_name_plural': '給与締めバック根拠',
                'ordering': ['cast_id', 'occurred_at', 'bill_id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRunLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_min', models.PositiveIntegerField(default=0, verbose_name='勤務分')),
                ('hourly_pay', models.PositiveIntegerField(default=0, verbose_name='時給合計')),
                ('commission', models.PositiveIntegerField(default=0, verbose_name='バック合計')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='給与合計')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.cast', verbose_name='キャスト')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.payrollrun')),
            ],
            options={
                'verbose_name': '給与締め明細',
                'verbose_name_plural': '給与締め明細',
                'ordering': ['cast__stage_name', 'cast_id'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['store', 'period_start', 'period_end'], name='billing_pay_store_i_655a48_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['created_at'], name='billing_pay_created_e22a07_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrunbackrow',
            index=models.Index(fields=['run', 'cast', 'bill_id'], name='billing_pay_run_id_a2b5a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrunline',
            unique_together={('run', 'cast')},
        ),
    ]
