# Generated by Django 4.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0104_bill_apply_service_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='内部コード（例: catch / free_info / referral）', max_length=40)),
                ('name', models.CharField(help_text='表示名（例: キャッチ / 無料案内所 / 紹介）', max_length=50)),
                ('description', models.TextField(blank=True, help_text='説明・使用ガイドライン')),
                ('color', models.CharField(blank=True, default='#FF9800', help_text='UI表示用カラーコード（例: #FF9800）', max_length=7)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_tags', to='billing.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '伝票タグ',
                'verbose_name_plural': '伝票タグ',
                'ordering': ['store', 'code'],
                'unique_together': {('store', 'code')},
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bills', to='billing.billtag', verbose_name='タグ'),
        ),
    ]
