# Generated by Django 5.2.1 on 2025-12-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0105_billtag_bill_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billtag',
            name='color',
        ),
    ]
