# Generated by Django 5.2.1 on 2025-12-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0106_remove_billtag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourlysalessummary',
            options={'ordering': ['date', 'hour'], 'verbose_name': '時間別売上サマリ', 'verbose_name_plural': '時間別売上サマリ'},
        ),
    ]
