# Generated by Django 5.2.1 on 2025-12-25 07:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0107_alter_hourlysalessummary_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='内部コード（例: taxi / meal / uniform）', max_length=40)),
                ('name', models.CharField(help_text='表示名（例: タクシー / 食事 / 制服）', max_length=50)),
                ('description', models.TextField(blank=True, help_text='説明・使用ガイドライン')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_expense_categories', to='billing.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '人件費経費カテゴリ',
                'verbose_name_plural': '人件費経費カテゴリ',
                'ordering': ['store', 'code'],
                'unique_together': {('store', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PersonnelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_role', models.CharField(help_text='cast/staff/manager（owner不可）', max_length=20, verbose_name='対象ロール')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='金額')),
                ('policy', models.CharField(choices=[('collect', '回収（立替）'), ('store_burden', '店舗負担')], default='collect', max_length=20, verbose_name='方針')),
                ('status', models.CharField(choices=[('open', '未回収'), ('settled', '回収済'), ('void', '無効')], db_index=True, default='open', max_length=20, verbose_name='ステータス')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='発生日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_expenses', to='billing.payrollrun', verbose_name='給与締め')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_expenses', to='billing.store', verbose_name='店舗')),
                ('subject_user', models.ForeignKey(help_text='cast/staff/managerのみ', on_delete=django.db.models.deletion.CASCADE, related_name='personnel_expenses', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='billing.personnelexpensecategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '人件費経費',
                'verbose_name_plural': '人件費経費',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelExpenseSettlementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='回収金額')),
                ('settled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='回収日時')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_events', to='billing.personnelexpense', verbose_name='経費')),
            ],
            options={
                'verbose_name': '経費回収イベント',
                'verbose_name_plural': '経費回収イベント',
                'ordering': ['-settled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='personnelexpense',
            index=models.Index(fields=['store', 'status', 'occurred_at'], name='billing_per_store_i_61c604_idx'),
        ),
        migrations.AddIndex(
            model_name='personnelexpense',
            index=models.Index(fields=['subject_user', 'status'], name='billing_per_subject_694538_idx'),
        ),
        migrations.AddIndex(
            model_name='personnelexpense',
            index=models.Index(fields=['payroll_run'], name='billing_per_payroll_767a59_idx'),
        ),
        migrations.AddIndex(
            model_name='personnelexpensesettlementevent',
            index=models.Index(fields=['expense', 'settled_at'], name='billing_per_expense_5e5790_idx'),
        ),
    ]
