# Generated by Django 5.2.1 on 2025-12-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0108_add_personnel_expense_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelexpense',
            name='subject_role',
            field=models.CharField(choices=[('cast', 'キャスト'), ('staff', 'スタッフ'), ('manager', 'マネージャー')], help_text='cast/staff/manager（owner不可）', max_length=20, verbose_name='対象ロール'),
        ),
    ]
