# Generated by Django 5.2.1 on 2025-12-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0109_alter_personnelexpense_subject_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountrule',
            name='code',
            field=models.SlugField(blank=True, help_text='内部コード（例: initial / agency / referral）', max_length=40, null=True),
        ),
    ]
