# Generated by Django 5.2.1 on 2026-01-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0110_alter_discountrule_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemmaster',
            name='uniq_store_code',
        ),

        # NOTE:
        # AlterUniqueTogether は DB に該当制約が存在しない環境があり migrate が落ちるため削除。
        # 以降の UniqueConstraint(AddConstraint) に一本化する。
        # migrations.AlterUniqueTogether(
        #     name='storeseatsetting',
        #     unique_together=set(),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='table',
        #     unique_together=set(),
        # ),

        migrations.AddConstraint(
            model_name='itemmaster',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(('code__isnull', True), _negated=True),
                    models.Q(('code', ''), _negated=True),
                ),
                fields=('store', 'code'),
                name='uniq_store_code',
            ),
        ),
        migrations.AddConstraint(
            model_name='storeseatsetting',
            constraint=models.UniqueConstraint(
                condition=models.Q(('seat_type__isnull', True), _negated=True),
                fields=('store', 'seat_type'),
                name='uniq_store_seat_type_nonnull',
            ),
        ),
        migrations.AddConstraint(
            model_name='storeseatsetting',
            constraint=models.UniqueConstraint(
                condition=models.Q(('seat_type__isnull', True)),
                fields=('store',),
                name='uniq_store_seat_type_null_single',
            ),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(('code__isnull', True), _negated=True),
                    models.Q(('code', ''), _negated=True),
                ),
                fields=('store', 'code'),
                name='uniq_table_store_code_nonnull',
            ),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(
                condition=models.Q(('code__isnull', True)),
                fields=('store',),
                name='uniq_table_store_null_code_single',
            ),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(
                condition=models.Q(('code', '')),
                fields=('store',),
                name='uniq_table_store_blank_code_single',
            ),
        ),
    ]