# Generated by Django 5.2.1 on 2026-01-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0111_remove_itemmaster_uniq_store_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billcustomer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='billtag',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='castcategoryrate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='castdailysummary',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hourlycastsales',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hourlysalessummary',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrunline',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='personnelexpensecategory',
            unique_together=set(),
        ),

        # NOTE:
        # storeseatsetting は DB 側で partial unique index
        # (uniq_store_seat_type_nonnull / uniq_store_seat_type_null_single)
        # を使って一意性を担保しており、Django の AlterUniqueTogether が
        # constraint を見つけられず migrate が落ちるため、ここはスキップする。
        # migrations.AlterUniqueTogether(
        #     name='storeseatsetting',
        #     unique_together=set(),
        # ),

        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='billcustomer',
            constraint=models.UniqueConstraint(fields=('bill', 'customer'), name='uniq_billcustomer_bill_customer'),
        ),
        migrations.AddConstraint(
            model_name='billtag',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='uniq_billtag_store_code'),
        ),
        migrations.AddConstraint(
            model_name='castcategoryrate',
            constraint=models.UniqueConstraint(fields=('cast', 'category'), name='uniq_castcategoryrate_cast_category'),
        ),
        migrations.AddConstraint(
            model_name='castdailysummary',
            constraint=models.UniqueConstraint(fields=('store', 'cast', 'work_date'), name='uniq_castdailysummary_store_cast_workdate'),
        ),
        migrations.AddConstraint(
            model_name='hourlycastsales',
            constraint=models.UniqueConstraint(fields=('hourly_summary', 'cast'), name='uniq_hourlycast_hourlysummary_cast'),
        ),
        migrations.AddConstraint(
            model_name='hourlysalessummary',
            constraint=models.UniqueConstraint(fields=('store', 'date', 'hour'), name='uniq_hourlysales_store_date_hour'),
        ),
        migrations.AddConstraint(
            model_name='payrollrunline',
            constraint=models.UniqueConstraint(fields=('run', 'cast'), name='uniq_payrollrunline_run_cast'),
        ),
        migrations.AddConstraint(
            model_name='personnelexpensecategory',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='uniq_personnelexpcat_store_code'),
        ),
    ]