# Generated by Django 5.2.1 on 2026-01-26 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0114_itemmaster_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='誰が注文したか（顧客集計用）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='billing.customer'),
        ),
    ]
