# Generated by Django 5.2.1 on 2026-01-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0115_billitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcustomer',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text='来店時刻', null=True),
        ),
        migrations.AddField(
            model_name='billcustomer',
            name='left_at',
            field=models.DateTimeField(blank=True, help_text='退店時刻', null=True),
        ),
        migrations.AddConstraint(
            model_name='billcustomer',
            constraint=models.CheckConstraint(condition=models.Q(('arrived_at__isnull', True), ('left_at__isnull', True), ('left_at__gte', models.F('arrived_at')), _connector='OR'), name='billcustomer_arrived_before_left'),
        ),
    ]
