# Generated by Django 5.2.1 on 2026-01-26 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0116_billcustomer_arrived_at_billcustomer_left_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillCustomerNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_nominations', to='billing.bill')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_nominations', to='billing.cast')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_nominations', to='billing.customer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bill', 'customer', 'cast'), name='uniq_billcustomernomination_bill_customer_cast')],
            },
        ),
    ]
