# Generated by Django 5.2.1 on 2026-01-26 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0117_billcustomernomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='ordered_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
