# Generated by Django 5.2.1 on 2026-01-28 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0118_billitem_ordered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcustomer',
            name='arrived_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='来店時刻', null=True),
        ),
    ]
