# Generated by Django 5.2.1 on 2026-01-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0119_alter_billcustomer_arrived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='exclude_from_nom_pool',
            field=models.BooleanField(default=False, help_text='本指名プールから除外（例: TC）'),
        ),
    ]
