# Generated by Django 5.2.1 on 2026-01-30 08:39

from django.db import migrations, models

def backfill_nomination_started_at(apps, schema_editor):
    BillCustomerNomination = apps.get_model('billing', 'BillCustomerNomination')
    BillCustomerNomination.objects.filter(started_at__isnull=True).update(
        started_at=models.F('created_at')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0120_itemcategory_exclude_from_nom_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcustomernomination',
            name='ended_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='指名終了時刻（NULL=継続中）', null=True),
        ),
        migrations.AddField(
            model_name='billcustomernomination',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='指名開始時刻', null=True),
        ),
        migrations.RunPython(backfill_nomination_started_at, migrations.RunPython.noop),
    ]
