# Generated by Django 5.2.1 on 2026-01-30

from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0121_add_timerange_to_nomination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcustomernomination',
            name='started_at',
            field=models.DateTimeField(db_index=True, help_text='指名開始時刻（必須）'),
        ),
        migrations.AddConstraint(
            model_name='billcustomernomination',
            constraint=models.CheckConstraint(condition=Q(('ended_at__isnull', True), _connector='OR') | Q(('ended_at__gte', F('started_at'))), name='nomination_started_before_ended'),
        ),
    ]
