# Generated by Django 5.2.1 on 2026-02-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0122_finalize_nomination_timerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='card_brand',
            field=models.CharField(blank=True, choices=[('visa', 'VISA'), ('mastercard', 'MasterCard'), ('jcb', 'JCB'), ('amex', 'AMEX'), ('diners', 'Diners')], db_index=True, help_text='カード種別（カード決済時のみ）', max_length=16, null=True),
        ),
    ]
