# Generated by Django 5.2.1 on 2026-02-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0123_bill_card_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tables',
            field=models.ManyToManyField(blank=True, help_text='複数卓対応（Phase1：FK table を残したまま追加）', related_name='bills_m2m', to='billing.table'),
        ),
    ]
