# Generated by Django 5.2.1 on 2026-02-03 10:19

from django.db import migrations


def forwards(apps, schema_editor):
    """既存の Bill.table (FK) から Bill.tables (M2M) へデータをバックフィル"""
    Bill = apps.get_model('billing', 'Bill')
    
    # table_id が NULL でない Bill のみ対象
    bills_with_table = Bill.objects.exclude(table_id__isnull=True)
    
    backfilled_count = 0
    for bill in bills_with_table.iterator():
        # M2M に追加（重複は自動回避される）
        bill.tables.add(bill.table_id)
        backfilled_count += 1
    
    print(f"✅ Backfilled {backfilled_count} bills (FK table → M2M tables)")


def backwards(apps, schema_editor):
    """逆マイグレーションは何もしない（FK は残すため）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0124_bill_tables'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
