# Generated by Django 5.2.1 on 2026-02-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0125_backfill_bill_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
