# Generated by Django 5.2.1 on 2026-02-20 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0126_bill_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItemCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='served_by_links', to='billing.billitem')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='served_bill_item_links', to='billing.cast')),
            ],
        ),
        migrations.AddField(
            model_name='billitem',
            name='served_by_casts',
            field=models.ManyToManyField(blank=True, related_name='served_items_m2m', through='billing.BillItemCast', to='billing.cast'),
        ),
        migrations.AddConstraint(
            model_name='billitemcast',
            constraint=models.UniqueConstraint(fields=('bill_item', 'cast'), name='uniq_billitem_cast'),
        ),
    ]
