# Generated by Django 5.2.1 on 2026-02-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0127_billitemcast_billitem_served_by_casts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrunbackrow',
            name='label',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='種別ラベル'),
        ),
        migrations.AddField(
            model_name='payrollrunline',
            name='garden_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='Garden制度スナップショット'),
        ),
    ]
