# Generated by Django 5.2.1 on 2026-03-12 04:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0128_garden_monthly_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSubstituteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('substitute_amount', models.PositiveIntegerField(default=0)),
                ('ordered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_items', to='billing.bill')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitute_items', to='billing.cast')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_items', to='billing.customer')),
                ('item_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitute_items', to='billing.itemmaster')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gte', 1), ('qty__lte', 99)), name='billsubstituteitem_qty_range'), models.CheckConstraint(condition=models.Q(('price__gte', 0), ('price__lte', 2000000)), name='billsubstituteitem_price_range')],
            },
        ),
    ]
