# Generated by Django 5.2.1 on 2026-03-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0130_payrollrunline_substitute_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='receipt_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='領収書宛名'),
        ),
    ]
