# Generated by Django 5.2.1 on 2026-03-31 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0131_add_receipt_name_to_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CastManualSubtotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='営業日')),
                ('manual_subtotal', models.IntegerField(default=0, verbose_name='キャスト売上（手入力）')),
                ('memo', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_subtotals', to='billing.cast')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_manual_subtotals', to='billing.store')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'キャスト売上（手入力）',
                'verbose_name_plural': 'キャスト売上（手入力）',
                'ordering': ['-work_date', 'cast__stage_name'],
                'indexes': [models.Index(fields=['store', 'work_date'], name='billing_cas_store_i_2449fc_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'cast', 'work_date'), name='uniq_castmanualsubtotal_store_cast_date')],
            },
        ),
    ]
