# Generated by Django 5.2.1 on 2026-04-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0140_storecategorypreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecategorypreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
