# Generated by Django 5.2.1 on 2025-06-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_castprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
