# Generated by Django 5.2.1 on 2025-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='castprofile',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='castprofile',
            name='ng_customers',
            field=models.ManyToManyField(blank=True, related_name='ng_casts_of', to='core.customer'),
        ),
    ]
