# Generated by Django 5.2.1 on 2025-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_castprofile_memo_castprofile_ng_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='received_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
