# Generated by Django 5.2.1 on 2025-06-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reservation_received_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deposited_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
