# Generated by Django 5.2.1 on 2025-06-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='castprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cast_photos/'),
        ),
    ]
