# Generated by Django 5.2.1 on 2025-06-19 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_castprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castprofile',
            name='user',
            field=models.ForeignKey(blank=True, help_text='このログインで管理画面・マイページに入れるキャストなら紐付ける', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cast_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
