# Generated by Django 5.2.1 on 2025-06-21 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_castprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcast',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='reservationcast',
            name='rank_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rankcourse'),
        ),
    ]
