# Generated by Django 5.2.1 on 2025-06-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reservationcast_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationcast',
            options={'verbose_name': 'キャスト', 'verbose_name_plural': 'キャスト'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='顧客'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver', verbose_name='ドライバー'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_at',
            field=models.DateTimeField(verbose_name='開始時刻'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('INSERVICE', 'In Service'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled')], default='BOOKED', max_length=10, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store', verbose_name='店舗'),
        ),
        migrations.AlterField(
            model_name='reservationcast',
            name='cast_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.castprofile', verbose_name='キャスト'),
        ),
        migrations.AlterField(
            model_name='reservationcast',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='コース（時間）'),
        ),
        migrations.AlterField(
            model_name='reservationcast',
            name='rank_course',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rankcourse'),
        ),
        migrations.AlterField(
            model_name='reservationcast',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reservation', verbose_name='予約'),
        ),
    ]
