# Generated by Django 5.2.1 on 2025-06-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_reservationcast_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationcast',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='コース'),
        ),
    ]
