# Generated by Django 5.2.1 on 2025-06-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_reservationcast_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='manual_extra_price',
            field=models.IntegerField(default=0, verbose_name='延長料金'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='received_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='受取金'),
        ),
    ]
