# Generated by Django 5.2.1 on 2025-06-21 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_reservation_manual_extra_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castprofile',
            options={'verbose_name': 'キャスト情報', 'verbose_name_plural': 'キャスト情報'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '顧客', 'verbose_name_plural': '顧客'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'オプション', 'verbose_name_plural': 'オプション'},
        ),
        migrations.AlterModelOptions(
            name='performer',
            options={'verbose_name': '予約', 'verbose_name_plural': '予約'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '予約', 'verbose_name_plural': '予約'},
        ),
        migrations.AlterField(
            model_name='reservationcast',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='core.reservation', verbose_name='予約'),
        ),
    ]
