# Generated by Django 5.2.1 on 2025-06-23 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_castprofile_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.driver', verbose_name='ドライバー'),
        ),
    ]
