# Generated by Django 5.2.1 on 2025-06-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_reservation_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.driver', verbose_name='ドライバー'),
        ),
    ]
