# Generated by Django 5.2.1 on 2025-06-24 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_reservation_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='address_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.customer')),
            ],
            options={
                'verbose_name': '顧客住所',
                'verbose_name_plural': '顧客住所',
                'unique_together': {('customer', 'address')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='address_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.customeraddress'),
        ),
    ]
