# Generated by Django 5.2.1 on 2025-06-24 14:51
# core/migrations/000X_migrate_customer_address.py
from django.db import migrations

def forwards(apps, schema_editor):
	Customer		 = apps.get_model('core', 'Customer')
	CustomerAddress	 = apps.get_model('core', 'CustomerAddress')

	bulk = []
	for c in Customer.objects.exclude(address='').iterator():
		bulk.append(
			CustomerAddress(
				customer	= c,
				label		='旧住所',
				address		=c.address,
				is_primary	=True,
			)
		)
	if bulk:
		CustomerAddress.objects.bulk_create(bulk)



class Migration(migrations.Migration):

	dependencies = [
		('core', '0019_reservation_address_text_customeraddress_and_more'),
	]

	operations = [
		migrations.RunPython(forwards, migrations.RunPython.noop),
	]
