# Generated by Django 5.2.1 on 2025-06-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_migrate_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
