# Generated by Django 5.2.1 on 2025-06-25 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_drop_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('memo', models.TextField(blank=True)),
                ('cast_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_plans', to='core.castprofile')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
            ],
            options={
                'ordering': ['date', 'start_at'],
                'unique_together': {('cast_profile', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ShiftAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('cast_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.castprofile')),
                ('shift_plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='core.shiftplan')),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
    ]
