# Generated by Django 5.2.1 on 2025-06-26 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_shiftplan_shiftattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PU', 'Pick-Up'), ('DO', 'Drop-Off'), ('BO', 'Both')], default='PU', max_length=2)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('collected_amount', models.PositiveIntegerField(blank=True, help_text='DO 時の現金回収額', null=True)),
                ('status', models.CharField(choices=[('PL', 'Planned'), ('IP', 'In Progress'), ('DN', 'Done')], default='PL', max_length=2)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.driver')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='core.reservation')),
            ],
            options={
                'ordering': ['start_at', 'role'],
                'unique_together': {('reservation', 'role')},
            },
        ),
    ]
