# Generated by Django 5.2.1 on 2025-06-27 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_reservation_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(choices=[('normal', '通常予約'), ('hime', '姫予約')], default='normal', max_length=10),
        ),
        migrations.CreateModel(
            name='ManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('revenue', '売上'), ('expense', '経費')], max_length=7)),
                ('label', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_entries', to='core.reservation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('card', 'カード'), ('cash', '現金')], max_length=5)),
                ('amount', models.PositiveIntegerField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.reservation')),
            ],
        ),
    ]
