# Generated by Django 5.2.1 on 2025-06-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_reservation_reservation_type_manualentry_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='extend_price_30',
            field=models.PositiveIntegerField(default=15000),
        ),
    ]
