# Generated by Django 5.2.1 on 2025-07-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rank_extend_price_30'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='車種'),
        ),
        migrations.AddField(
            model_name='driver',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='driver',
            name='ng_casts',
            field=models.ManyToManyField(blank=True, related_name='ng_drivers', to='core.castprofile', verbose_name='キャスト NG'),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
    ]
