# Generated by Django 5.2.1 on 2025-07-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_driver_car_type_driver_memo_driver_ng_casts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='nubmer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ナンバー'),
        ),
    ]
