# Generated by Django 5.2.1 on 2025-07-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_driver_nubmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='nubmer',
            new_name='number',
        ),
    ]
