# Generated by Django 5.2.1 on 2025-07-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_nubmer_driver_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='change_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='お釣り'),
        ),
    ]
