# Generated by Django 5.2.1 on 2025-07-02 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_reservation_change_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('float_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='出勤時釣り銭')),
                ('clock_in_at', models.DateTimeField(blank=True, null=True)),
                ('total_received', models.PositiveIntegerField(default=0, verbose_name='総受取金')),
                ('used_float', models.PositiveIntegerField(default=0, verbose_name='使用釣り銭')),
                ('expenses', models.PositiveIntegerField(default=0, verbose_name='経費')),
                ('actual_cash', models.PositiveIntegerField(blank=True, null=True, verbose_name='実際の所持金')),
                ('actual_deposit', models.PositiveIntegerField(blank=True, null=True, verbose_name='店舗入金額')),
                ('float_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='締め釣り銭')),
                ('diff_reason', models.TextField(blank=True)),
                ('manager_checked', models.BooleanField(default=False)),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.driver')),
            ],
            options={
                'verbose_name': 'ドライバー日報',
                'verbose_name_plural': 'ドライバー日報',
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
