# Generated by Django 5.2.1 on 2025-07-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_drivershift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivershift',
            name='total_received',
            field=models.IntegerField(default=0),
        ),
    ]
