# Generated by Django 5.2.1 on 2025-07-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_drivershift_total_received'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationdriver',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='reservationdriver',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reservationdriver',
            constraint=models.UniqueConstraint(fields=('reservation', 'driver', 'role'), name='unique_reservation_driver_role'),
        ),
        migrations.RemoveField(
            model_name='reservationdriver',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='reservationdriver',
            name='start_at',
        ),
    ]
