# Generated by Django 5.2.1 on 2025-07-03 04:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_reservationdriver_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '経費科目',
                'verbose_name_plural': '経費科目',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('amount', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.expensecategory')),
                ('store', models.ForeignKey(blank=True, help_text='NULL＝全店舗共通', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.store')),
            ],
            options={
                'verbose_name': '経費',
                'verbose_name_plural': '経費',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CastRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('cast_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='core.castprofile')),
            ],
            options={
                'verbose_name': 'キャスト時給',
                'verbose_name_plural': 'キャスト時給履歴',
                'ordering': ['cast_profile', 'effective_from'],
                'unique_together': {('cast_profile', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='DriverRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='core.driver')),
            ],
            options={
                'verbose_name': 'ドライバー時給',
                'verbose_name_plural': 'ドライバー時給履歴',
                'ordering': ['driver', 'effective_from'],
                'unique_together': {('driver', 'effective_from')},
            },
        ),
    ]
