# Generated by Django 5.2.1 on 2025-07-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_expensecategory_expenseentry_castrate_driverrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='is_default',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='is_fixed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
