# Generated by Django 5.2.1 on 2025-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_expensecategory_is_default_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castrate',
            options={'ordering': ['cast_profile', 'effective_from'], 'verbose_name': 'キャスト歩合', 'verbose_name_plural': 'キャスト時給履歴'},
        ),
        migrations.AddField(
            model_name='castrate',
            name='commission_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='指名料に掛ける %', max_digits=5, null=True),
        ),
    ]
