# Generated by Django 5.2.1 on 2025-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_old_to_initial_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='label',
            field=models.CharField(blank=True, default='初回住所', max_length=30),
        ),
    ]
