# Generated by Django 5.2.1 on 2025-07-07 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_customeraddress_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastStandbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('cast_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standby_places', to='core.castprofile')),
            ],
            options={
                'verbose_name': '待機場所',
                'verbose_name_plural': '待機場所',
                'unique_together': {('cast_profile', 'address')},
            },
        ),
    ]
