# Generated by Django 5.2.1 on 2025-07-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_caststandbyplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='caststandbyplace',
            name='zipcode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
