# Generated by Django 5.2.1 on 2025-07-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_caststandbyplace_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('CALL_PENDING', '確認電話[未]'), ('CALL_DONE', '確認電話[済]'), ('BOOKED', '仮予約'), ('IN_SERVICE', '接客開始'), ('CASH_COLLECT', '集金[済]')], default='BOOKED', max_length=30, verbose_name='ステータス'),
        ),
    ]
