# Generated by Django 5.1.6 on 2025-02-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='お客様の名前')),
                ('start_time', models.DateTimeField(verbose_name='予約開始時刻')),
            ],
        ),
    ]
