# Generated by Django 5.1.6 on 2025-02-27 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('reservation', '0002_course_menu_reservation_course_reservation_menus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cast',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'cast'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='キャスト'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.store', verbose_name='店舗'),
        ),
    ]
