# Generated by Django 5.2.1 on 2025-09-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_storemembership'),
        ('billing', '0058_itemcategory_route_alter_itemmaster_route'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='unique_primary_membership_per_user'),
        ),
    ]
