# Generated by Django 5.2.1 on 2025-12-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_storemembership_unique_primary_membership_per_user'),
        ('billing', '0092_alter_bill_opened_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storemembership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='storemembership',
            constraint=models.UniqueConstraint(fields=('user', 'store'), name='uniq_storemembership_user_store'),
        ),
    ]
