// @ts-nocheck
// frontend/scripts/gen-version.cjs
const { execSync } = require('node:child_process');
const { readFileSync, writeFileSync, mkdirSync } = require('node:fs');
const { resolve } = require('node:path');

const FRONT = resolve(__dirname, '..');   // frontend/
const SRC   = resolve(FRONT, 'src');
const PKG_F = resolve(FRONT, 'package.json');

const now = new Date();
const jst = new Date(now.getTime() + 9*60*60*1000); // UTC→JST(+09:00)
const buildAt = jst.toISOString().replace('Z', '+09:00'); // 例: 2025-11-04T15:27:00+09:00

function shortSha() {
  // CI/ホスティングが用意する変数を順に優先
  const envSha =
    process.env.GITHUB_SHA ||
    process.env.VERCEL_GIT_COMMIT_SHA ||
    process.env.COMMIT_REF ||            // Netlify
    process.env.SOURCE_VERSION ||        // Heroku
    process.env.RENDER_GIT_COMMIT ||     // Render
    '';
  if (envSha) return String(envSha).slice(0, 7);
  try { return execSync('git rev-parse --short HEAD').toString().trim(); } catch { return 'nogit'; }
}

function calVerJST() {
  // すでに上で作ってる jst を使う（UTC+9）
  const d = jst;
  const y = String(d.getUTCFullYear()).slice(-2);
  const M = String(d.getUTCMonth()+1).padStart(2,'0');
  const D = String(d.getUTCDate()).padStart(2,'0');
  const h = String(d.getUTCHours()).padStart(2,'0');
  const m = String(d.getUTCMinutes()).padStart(2,'0');
  return `${y}.${M}.${D}.${h}.${m}`;
}
let appVersion =
  process.env.APP_VERSION ||                    // CIで明示指定があれば最優先
  '';                                          // 何も無ければ後でCalVer採用

const sha = shortSha();

// タグ/packge.jsonが空なら CalVer+SHA を使う（手上げ不要）
if (!appVersion) appVersion = `${calVerJST()}+${sha}`;

const out =
  '// AUTO-GENERATED. DO NOT EDIT.\n' +
  '// Generated by scripts/gen-version.cjs\n' +
  "export const APP_VERSION = '" + appVersion + "';\n" +
  "export const GIT_SHA     = '" + sha + "';\n" +
  "export const BUILD_AT    = '" + buildAt + "';\n";

mkdirSync(SRC, { recursive: true });
writeFileSync(resolve(SRC, 'version.gen.js'), out);
console.log('[version] ' + appVersion + ' (' + sha + ') @ ' + buildAt);
