// @ts-nocheck
// frontend/scripts/gen-version.cjs  (CJS)
const { execSync } = require('node:child_process');
const { readFileSync, writeFileSync, mkdirSync } = require('node:fs');
const { resolve } = require('node:path');

const FRONT = resolve(__dirname, '..');   // frontend/
const SRC   = resolve(FRONT, 'src');
const PKG_F = resolve(FRONT, 'package.json');

// === 時刻（JST固定） =========================================================
const now = new Date();
const jst = new Date(now.getTime() + 9*60*60*1000); // UTC→JST(+09:00)
const buildAt = jst.toISOString().replace('Z', '+09:00'); // 例: 2025-11-04T15:27:00+09:00

// === 短SHA ===================================================================
function shortSha() {
  const envSha =
    process.env.GITHUB_SHA ||
    process.env.VERCEL_GIT_COMMIT_SHA ||
    process.env.COMMIT_REF ||            // Netlify
    process.env.SOURCE_VERSION ||        // Heroku
    process.env.RENDER_GIT_COMMIT ||     // Render
    '';
  if (envSha) return String(envSha).slice(0, 7);
  try { return execSync('git rev-parse --short HEAD').toString().trim(); }
  catch { return 'nogit'; }
}

// === CalVer (JST) ============================================================
function calVerJST() {
  const d = jst;
  const pad = n => String(n).padStart(2, '0');
  const y = String(d.getUTCFullYear()).slice(-2);
  const M = pad(d.getUTCMonth()+1);
  const D = pad(d.getUTCDate());
  const h = pad(d.getUTCHours());
  const m = pad(d.getUTCMinutes());
  return `${y}.${M}.${D}.${h}.${m}`;     // 例: 25.11.04.15.27
}

// === APP_VERSION 決定（env優先／なければ CalVer+SHA） =======================
let appVersion = process.env.APP_VERSION || '';  // ← envで上書きしたいときだけ指定
const sha = shortSha();
if (!appVersion) appVersion = `${calVerJST()}+${sha}`;

// === version.gen.js 出力 ======================================================
mkdirSync(SRC, { recursive: true });
const jsOut =
  '// AUTO-GENERATED. DO NOT EDIT.\n' +
  '// Generated by scripts/gen-version.cjs\n' +
  "export const APP_VERSION = '" + appVersion + "';\n" +
  "export const GIT_SHA     = '" + sha + "';\n" +
  "export const BUILD_AT    = '" + buildAt + "';\n";
writeFileSync(resolve(SRC, 'version.gen.js'), jsOut);

// === version.json（/version.json で配信される） ==============================
mkdirSync(resolve(FRONT, 'public'), { recursive: true });
writeFileSync(
  resolve(FRONT, 'public', 'version.json'),
  JSON.stringify({ app_version: appVersion, git_sha: sha, build_at: buildAt }, null, 2)
);

console.log('[version]', appVersion, `(${sha})`, '@', buildAt);
