# Generated by Django 5.2.1 on 2025-06-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_reservationcast_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSetting',
            fields=[
            ],
            options={
                'verbose_name': 'コース',
                'verbose_name_plural': 'コース',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.course',),
        ),
        migrations.CreateModel(
            name='DriverSetting',
            fields=[
            ],
            options={
                'verbose_name': 'スタッフ',
                'verbose_name_plural': 'スタッフ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.driver',),
        ),
        migrations.CreateModel(
            name='GroupOptionPriceSetting',
            fields=[
            ],
            options={
                'verbose_name': 'グループオプション料金',
                'verbose_name_plural': 'グループオプション料金',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.groupoptionprice',),
        ),
        migrations.CreateModel(
            name='RankCourseSetting',
            fields=[
            ],
            options={
                'verbose_name': 'ランク別料金',
                'verbose_name_plural': 'ランク別料金',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.rankcourse',),
        ),
        migrations.CreateModel(
            name='RankSetting',
            fields=[
            ],
            options={
                'verbose_name': 'ランク',
                'verbose_name_plural': 'ランク',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.rank',),
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.store',),
        ),
    ]
