// AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/gen-version.cjs
export const APP_VERSION = '25.12.05.18.40+nogit';
export const GIT_SHA     = 'nogit';
export const BUILD_AT    = '2025-12-05T18:40:23.355+09:00';
