// AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/gen-version.cjs
export const APP_VERSION = '26.04.03.20.54+f0109d88';
export const GIT_SHA     = 'f0109d88';
export const BUILD_AT    = '2026-04-03T20:54:51.753+09:00';
