// AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/gen-version.cjs
export const APP_VERSION = '25.12.08.15.30+7ae5bdbb';
export const GIT_SHA     = '7ae5bdbb';
export const BUILD_AT    = '2025-12-08T15:30:08.006+09:00';
