# Generated by Django 5.2.1 on 2025-06-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_alter_castprofile_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowProxy',
            fields=[
            ],
            options={
                'verbose_name': '入出金',
                'verbose_name_plural': '入出金',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.cashflow',),
        ),
        migrations.CreateModel(
            name='CastCoursePriceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'キャスト-コース個別価格',
                'verbose_name_plural': 'キャスト-コース個別価格',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.castcourseprice',),
        ),
        migrations.CreateModel(
            name='CastOptionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'キャスト-オプション個別価格',
                'verbose_name_plural': 'キャスト-オプション個別価格',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.castoption',),
        ),
        migrations.CreateModel(
            name='CourseProxy',
            fields=[
            ],
            options={
                'verbose_name': 'コース',
                'verbose_name_plural': 'コース',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.course',),
        ),
        migrations.CreateModel(
            name='DriverProxy',
            fields=[
            ],
            options={
                'verbose_name': 'スタッフ',
                'verbose_name_plural': 'スタッフ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.driver',),
        ),
        migrations.CreateModel(
            name='GroupOptionPriceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'グループオプション料金',
                'verbose_name_plural': 'グループオプション料金',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.groupoptionprice',),
        ),
        migrations.CreateModel(
            name='RankCourseProxy',
            fields=[
            ],
            options={
                'verbose_name': 'ランク別料金',
                'verbose_name_plural': 'ランク別料金',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.rankcourse',),
        ),
        migrations.CreateModel(
            name='RankProxy',
            fields=[
            ],
            options={
                'verbose_name': 'ランク',
                'verbose_name_plural': 'ランク',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.rank',),
        ),
        migrations.CreateModel(
            name='ReservationCastProxy',
            fields=[
            ],
            options={
                'verbose_name': '予約-キャスト行',
                'verbose_name_plural': '予約-キャスト行',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.reservationcast',),
        ),
        migrations.CreateModel(
            name='ReservationChargeProxy',
            fields=[
            ],
            options={
                'verbose_name': '予約-追加料金行',
                'verbose_name_plural': '予約-追加料金行',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.reservationcharge',),
        ),
        migrations.CreateModel(
            name='StoreProxy',
            fields=[
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.store',),
        ),
    ]
