# Generated by Django 5.1.6 on 2025-02-27 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_cast_reservation_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cast_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='キャスト受取金'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_reservations', to=settings.AUTH_USER_MODEL, verbose_name='ドライバー'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='driver_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ドライバー受取金'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='store_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='店舗受取金'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cast',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'cast'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cast_reservations', to=settings.AUTH_USER_MODEL, verbose_name='キャスト'),
        ),
    ]
