# Generated by Django 5.1.6 on 2025-03-04 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_storeuser_rank_alter_storeuser_star_count_and_more'),
        ('reservation', '0009_reservation_cast_received_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='store_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.storeuser', verbose_name='店舗×キャスト'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_as_cast', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.course'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='reservation.discount'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_as_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='enrollment_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='enrollment_fee_discounted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='membership_type',
            field=models.CharField(choices=[('new', '新規'), ('general', '一般会員'), ('member', '本会員')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='menus',
            field=models.ManyToManyField(blank=True, to='reservation.menu'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='photo_nomination_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='photo_nomination_fee_discounted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='regular_nomination_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='regular_nomination_fee_discounted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
