# Generated by Django 5.1.6 on 2025-03-10 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_storeuser_rank_alter_storeuser_star_count_and_more'),
        ('reservation', '0010_reservation_store_user_alter_reservation_cast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.course', verbose_name='コース'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='reservation.discount', verbose_name='適用割引'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='enrollment_fee',
            field=models.BooleanField(default=False, verbose_name='入会金あり'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='enrollment_fee_discounted',
            field=models.BooleanField(default=True, verbose_name='入会金0円割引'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='membership_type',
            field=models.CharField(choices=[('new', '新規'), ('general', '一般会員'), ('member', '本会員')], default='general', max_length=50, verbose_name='会員種別'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='menus',
            field=models.ManyToManyField(blank=True, to='reservation.menu', verbose_name='メニュー'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='photo_nomination_fee',
            field=models.BooleanField(default=False, verbose_name='写真指名あり'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='photo_nomination_fee_discounted',
            field=models.BooleanField(default=True, verbose_name='写真指名0円割引'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='regular_nomination_fee',
            field=models.BooleanField(default=False, verbose_name='本指名あり'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='regular_nomination_fee_discounted',
            field=models.BooleanField(default=True, verbose_name='本指名割引'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='予約金'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='予約開始時刻'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.store', verbose_name='店舗'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='予約時間（分）'),
        ),
    ]
